mqtt:
#  address: 192.168.178.35
  address: 192.168.2.116
#  address: 192.168.2.196
  port: 1883
  topic: "temp/pico"
dataDir: "./data"
sensors:
  - "pico_fb"
  - "pico_ft"
  - "pico_bb"
  - "pico_bt"
webUI:
  host: "0.0.0.0"
  port: 8080